### ISSUE TITLE
nextEffect 的疑问

### ISSUE THREAD

**Issue by 282159468** [y805939188/simple-react#1]
https://github.com/y805939188/simple-react/tree/master/procedure/%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB/fiber2

        <div>                           <div id="haschange">
            <h1>123</h1>                    <h1>456</h1>
            <h2>text</h2>    setState       <h2>text</h2>
            <span>          ——————————→     <span class="haschange">
                <a>888</a>                     <a>888</a>
                <p></p>                     </span>    
            </span>                         <h3>333</h3>
        </div>                          </div>
![image](https://user-images.githubusercontent.com/28442945/85216412-e8d64e00-b3b6-11ea-9255-478175abb06f.png)

这两名看起来矛盾了

**Comment by y805939188** [comment]
> https://github.com/y805939188/simple-react/tree/master/procedure/%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB/fiber2
> 
> ```
>     <div>                           <div id="haschange">
>         <h1>123</h1>                    <h1>456</h1>
>         <h2>text</h2>    setState       <h2>text</h2>
>         <span>          ——————————→     <span class="haschange">
>             <a>888</a>                     <a>888</a>
>             <p></p>                     </span>    
>         </span>                         <h3>333</h3>
>     </div>                          </div>
> ```
> 
> ![image](https://user-images.githubusercontent.com/28442945/85216412-e8d64e00-b3b6-11ea-9255-478175abb06f.png)
> 
> 这两名看起来矛盾了

谢谢指出，已订正~
